name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  REGISTRY: donkeystudio
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
      with:
        use: linux/amd64,linux/arm64,linux/arm/v7
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_KEY }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.0.0
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
