name: Docker Image CI

on:
  workflow_dispatch
    
env:
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push:
    name: Push Docker image to Docker Hub
    runs-on: [self-hosted]
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_KEY }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.0.0
      with:
        push: true
        context: .
        tags: ${{ env.IMAGE_NAME }}:latest
        platforms: linux/amd64,linux/arm64,linux/arm/v7
